from django.urls import path

from core import views, library_browse, library_drafts, library_export, library_pdf, library_solutions, library_question_editor, library_tags, api_key_reveal, export_preferences, practice

urlpatterns = [
    path("", views.index_page),
    path("library", views.library_page),
    path("practice/<uuid:paper_id>", practice.page),
    path("practice.js", views._frontend("practice.js", "application/javascript; charset=utf-8")),
    path("shortcut-help.js", views._frontend("shortcut-help.js", "application/javascript; charset=utf-8")),
    path("settings", views.index_page),
    path("app.js", views.app_script),
    path("browser-interactions.js", views.browser_interactions_script),
    path("site-drawer.js", views.site_drawer_script),
    path("qb-render.js", views.render_script),
    path("library.js", views.library_script),
    path("library-workspace.js", views.library_workspace_script),
    path("library-solutions.js", views.library_solutions_script),
    path("library-answer-editor.js", views.library_answer_editor_script),
    path("library-question-editor.js", views.library_question_editor_script),
    path("library-question-viewer.js", views.library_question_viewer_script),
    path("exam-export.js", views.exam_export_script),
    path("exam-layout.js", views.exam_layout_script),
    path("static/library-ai-settings.js", views.library_ai_script),
    path("static/export-settings.js", views.export_settings_script),
    path("styles.css", views.styles),
    path("library.css", views.library_styles),
    path("favicon.png", views.favicon),
    path("vendor/katex/<path:asset>", views.katex_asset),
    path("api/health", views.health),
    path("api/status", views.status),
    path("api/settings/credentials", views.credential_settings_view),
    path("api/settings/credentials/key/reveal", api_key_reveal.credential_reveal_view),
    path("api/settings/models", views.model_settings),
    path("api/settings/features", views.feature_settings),
    path("api/settings/knowledge", views.knowledge_catalogue),
    path("api/settings/library-ai", views.library_ai_settings_view),
    path("api/settings/library-ai/share-reading-key", views.library_ai_share_reading_key_view),
    path("api/settings/library-ai/test", views.library_ai_test_view),
    path("api/settings/library-ai/key/reveal", api_key_reveal.reveal_view),
    path("api/export-preferences", export_preferences.preferences_view),
    path("api/export-preferences/select", export_preferences.select_export_directory_view),
    path("api/export-preferences/open", export_preferences.open_export_view),
    path("api/papers", views.papers),
    path("api/demo", views.demo_paper),
    path("api/demo/<uuid:paper_id>/library", practice.library_view),
    path("api/demo/<uuid:paper_id>/preview", practice.output_view, {"preview": True}),
    path("api/demo/<uuid:paper_id>/export-pdf", practice.output_view),
    path("api/papers/<uuid:paper_id>", views.paper_detail),
    path("api/papers/<uuid:paper_id>/pages/<int:page>/preview", views.page_preview),
    path("api/papers/<uuid:paper_id>/processing", views.paper_processing),
    path("api/papers/<uuid:paper_id>/continue-ai-cut", views.paper_continue_ai_cut),
    path("api/papers/<uuid:paper_id>/retry", views.paper_retry),
    path("api/papers/<uuid:paper_id>/reparse", views.paper_reparse),
    path("api/papers/<uuid:paper_id>/stop", views.paper_stop),
    path("api/papers/<uuid:paper_id>/read-cut-questions", views.paper_read_cut_questions),
    path("api/papers/<uuid:paper_id>/stop-cut-reading", views.paper_stop_cut_reading),
    path("api/papers/<uuid:paper_id>/resegment/preview", views.paper_resegment_preview),
    path("api/papers/<uuid:paper_id>/resegment", views.paper_resegment),
    path("api/papers/<uuid:paper_id>/archive", views.paper_archive),
    path("api/papers/<uuid:paper_id>/restore", views.paper_restore),
    path("api/papers/<uuid:paper_id>/split", views.paper_split),
    path("api/papers/<uuid:paper_id>/confirm-structure", views.paper_confirm_structure),
    path("api/papers/<uuid:paper_id>/page-order", views.paper_page_order),
    path("api/papers/<uuid:paper_id>/approve-green", views.approve_green),
    path("api/papers/<uuid:paper_id>/publish", views.publish_paper),
    path("api/papers/<uuid:paper_id>/questions", views.add_question),
    path("api/papers/<uuid:paper_id>/questions/delete", views.paper_questions_delete),
    path("api/papers/<uuid:paper_id>/question-trash", views.paper_question_trash),
    path(
        "api/papers/<uuid:paper_id>/question-trash/<uuid:batch_id>/restore",
        views.question_deletion_restore,
    ),
    # 正式题库页面沿用 M3 的地址查看出处
    path("api/documents/<uuid:paper_id>/pages/<int:page>/preview", views.page_preview),
    path("api/questions/<int:question_id>", views.question_delete),
    path("api/questions/<int:question_id>/figures/<int:index>", views.question_figure),
    path("api/questions/<int:question_id>/question-images/<int:index>", views.question_image),
    path("api/questions/<int:question_id>/ocr-figures/<int:index>", views.question_ocr_figure),
    path("api/questions/<int:question_id>/crop", views.question_crop),
    path("api/questions/<int:question_id>/region-read", views.question_region_read),
    path("api/questions/<int:question_id>/<str:action>", views.question_action),
    path("api/m3/papers", views.m3_papers),
    path("api/library", views.library_list),
    path("api/library/batch", library_browse.library_batch),
    path("api/library/withdraw-batch", views.library_withdraw_batch),
    path("api/library/export-docx", library_export.export_docx_view),
    path("api/library/export-pdf", library_pdf.export_pdf_view),
    path("api/library/drafts", library_drafts.drafts_view),
    path("api/library/drafts/<uuid:draft_id>", library_drafts.draft_detail),
    path("api/library/jobs", views.library_jobs_view),
    path("api/library/jobs/cancel", views.library_jobs_cancel),
    path("api/library/assistant/tasks", views.library_assistant_tasks),
    path("api/library/assistant/prepare", views.library_assistant_prepare),
    path("api/library/assistant/complete", views.library_assistant_complete),
    path("api/library/<uuid:publication_id>/solution", library_solutions.solution_view),
    path("api/library/<uuid:publication_id>/question", library_question_editor.question_editor),
    path("api/library/<uuid:publication_id>/tags", library_tags.tags_view),
    path("api/library/<uuid:publication_id>/solution-images", library_solutions.image_upload),
    path("api/library/<uuid:publication_id>/solution-images/<uuid:asset_id>", library_solutions.image_view),
    path("api/library/<uuid:publication_id>", views.library_detail),
    path("api/library/<uuid:publication_id>/figures/<str:name>", views.library_figure),
    path("api/library/<uuid:publication_id>/question-images/<str:name>", views.library_question_image),
    path("api/library/<uuid:publication_id>/pages/<int:page>", views.library_source_page),
    path("api/library/<uuid:publication_id>/crop", views.library_crop),
    path("api/library/<uuid:publication_id>/withdraw", views.library_withdraw),
]
