"use strict";
const assert = require("node:assert/strict");
const { nextCropNumber, cropDraftSnapshot, moveCropBox, createEditGuard, protectBeforeUnload } = require("./app.js");

assert.equal(nextCropNumber([{ number: 1 }, { number: 2 }, { number: 4 }]), 3, "Missing numbers may be filled without renumbering existing questions");
assert.equal(nextCropNumber([{ number: 8 }, { number: 9 }], 8), 10, "Continuing skips already occupied numbers");
assert.equal(nextCropNumber([{ number: 999 }, { number: 1 }], 999), 2, "The last supported number wraps safely");
assert.equal(nextCropNumber([{ number: 1, group: { id: 12 } }, { number: 2, group: { id: 13 } }], 1, 13), 1, "Different groups have their own numbering");
assert.equal(nextCropNumber(Array.from({ length: 999 }, (_, i) => ({ number: i + 1 }))), null, "A full group must not suggest a duplicate");
assert.deepEqual(moveCropBox([2, 4, 202, 104], -5, -20), [0, 0, 200, 100], "Edge movement preserves crop width and height");
assert.deepEqual(moveCropBox([800, 850, 999, 998], 20, 20), [801, 852, 1000, 1000]);
assert.deepEqual(moveCropBox([10.1, 20.2, 300.3, 400.4], 5, 0), [15.1, 20.2, 305.3, 400.4]);

(async () => {
  let boxes = [{ page_idx: 1, bbox: [20, 30, 800, 200] }, { page_idx: 0, bbox: [10, 10, 500, 300] }];
  let number = "3", group = "12", ignored = [];
  const guard = createEditGuard();
  let closed = 0, resumed = 0;
  const track = () => guard.track("crop", () => cropDraftSnapshot(boxes, number, group, ignored), () => { closed += 1; guard.release("crop"); }, () => { resumed += 1; });
  track();
  assert.equal(guard.hasPendingWork(), false, "Opening a saved range does not warn");
  boxes.reverse();
  assert.equal(guard.hasPendingWork(), true, "Cross-page order is part of the draft");
  assert.equal(await guard.discard(async () => false, ["crop"]), false);
  assert.equal(resumed, 1); assert.equal(closed, 0);
  assert.equal(boxes[0].page_idx, 0, "Continue adjusting keeps the entire cross-page draft");
  guard.setSaving("crop", true);
  assert.equal(await guard.discard(async () => { throw Error("Must not ask while saving"); }, ["crop"]), false);
  guard.setSaving("crop", false);
  assert.equal(guard.hasPendingWork(), true, "A failed save leaves the crop dirty for retry");
  const event = { preventDefault() { this.prevented = true; } };
  assert.equal(protectBeforeUnload(event, guard), true);
  assert.equal(event.prevented, true);
  assert.equal(event.returnValue, "");
  track();
  assert.equal(guard.hasPendingWork(), false, "Successful save becomes the new baseline");
  group = "13";
  assert.equal(guard.hasPendingWork(), true, "Group changes must be protected alongside boxes");
  group = "12";
  boxes[0].label_offset = { x: 5, y: 12 };
  assert.equal(guard.hasPendingWork(), true, "Saved figure label offsets are real draft changes");
  delete boxes[0].label_offset;
  assert.equal(guard.hasPendingWork(), false);
  ignored = ["0:1,2,3,4"];
  assert.equal(guard.hasPendingWork(), true, "Ignoring a figure candidate must not be silently discarded");
  assert.equal(await guard.discard(async () => true, ["crop"]), true);
  assert.equal(closed, 1);
  assert.equal(guard.hasPendingWork(), false);
  const original = cropDraftSnapshot(boxes, number, group, ignored);
  boxes[0].bbox[0] = 999;
  assert.notEqual(original.boxes[0].bbox[0], 999, "The baseline is detached from mutable crop coordinates");
  console.log("Manual crop numbering, boundary movement, draft loss, save failure and unload protection: OK");
})().catch((error) => { console.error(error); process.exitCode = 1; });
