# TiYouJu (question-bank-card) one-line installer / updater for Windows.
#
#   irm https://github.com/CEHNICA/question-bank-card/releases/latest/download/install.ps1 | iex
#
# Finds the latest release on GitHub, downloads the installer, checks its
# SHA-256 (GitHub's asset digest, else SHA256SUMS.txt), backs up the question
# bank database, closes a running app, installs silently for the current user
# and starts the app.  It never asks for or touches API keys.
#
# Optional environment variables:
#   TIYOUJU_VERSION   install this version (e.g. 1.9.0) instead of the latest
#   TIYOUJU_MIRROR    prefix for download URLs (a GitHub download mirror)
#   TIYOUJU_REINSTALL set to 1 to reinstall the same version
#   TIYOUJU_NO_START  set to 1 to leave the app closed afterwards
#
# This file is generated by packaging/make_install_ps1.py (keep it ASCII).

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

function M([string]$key) { return [regex]::Unescape($Messages[$key]) }
$Messages = @{
    'finding' = '\u6b63\u5728\u67e5\u627e\u9898\u6709\u636e\u7684\u6700\u65b0\u7248\u672c\u2026\u2026'
    'offline' = '\u8fde\u4e0d\u4e0a GitHub\u3002\u8bf7\u68c0\u67e5\u7f51\u7edc\uff1b\u56fd\u5185\u7f51\u7edc\u53ef\u4ee5\u5148\u8bbe\u7f6e\u73af\u5883\u53d8\u91cf TIYOUJU_MIRROR \u4e3a GitHub \u4e0b\u8f7d\u52a0\u901f\u5730\u5740\uff0c\u6216\u5230 https://github.com/CEHNICA/question-bank-card/releases/latest \u624b\u52a8\u4e0b\u8f7d\u5b89\u88c5\u5305\u3002'
    'no_asset' = '\u8fd9\u4e2a\u7248\u672c\u91cc\u6ca1\u6709\u627e\u5230\u5b89\u88c5\u5305\u3002'
    'already' = '\u5df2\u7ecf\u662f\u6700\u65b0\u7248\uff1a'
    'downloading' = '\u6b63\u5728\u4e0b\u8f7d\uff1a'
    'bad_hash' = '\u5b89\u88c5\u5305\u7684 SHA-256 \u6821\u9a8c\u503c\u5bf9\u4e0d\u4e0a\uff0c\u5df2\u505c\u6b62\u5b89\u88c5\uff08\u53ef\u80fd\u4e0b\u8f7d\u4e0d\u5b8c\u6574\u6216\u88ab\u6539\u52a8\uff09\u3002\u8bf7\u91cd\u65b0\u8fd0\u884c\uff0c\u6216\u5230 GitHub \u53d1\u5e03\u9875\u624b\u52a8\u4e0b\u8f7d\u3002'
    'hash_ok' = 'SHA-256 \u6821\u9a8c\u901a\u8fc7\u3002'
    'closing' = '\u6b63\u5728\u5173\u95ed\u9898\u6709\u636e\u2026\u2026'
    'still_running' = '\u9898\u6709\u636e\u6ca1\u80fd\u5173\u6389\uff0c\u8bf7\u5148\u624b\u52a8\u5173\u6389\u5b83\u518d\u8fd0\u884c\u4e00\u6b21\u3002'
    'backup' = '\u9898\u5e93\u5df2\u5907\u4efd\u5230\uff1a'
    'installing' = '\u6b63\u5728\u5b89\u88c5\uff08\u4e0d\u4f1a\u5f39\u51fa\u7a97\u53e3\uff0c\u7ea6\u534a\u5206\u949f\uff09\u2026\u2026'
    'setup_failed' = '\u5b89\u88c5\u7a0b\u5e8f\u51fa\u9519\uff0c\u9000\u51fa\u7801\uff1a'
    'installed' = '\u9898\u6709\u636e\u5df2\u5b89\u88c5\uff0c\u7248\u672c\uff1a'
    'starting' = '\u6b63\u5728\u6253\u5f00\u9898\u6709\u636e\u2026\u2026'
    'cli' = '\u7ed9 AI \u52a9\u624b\u7528\u7684\u547d\u4ee4\u884c\uff1a'
    'cli_hint' = '\u8bd5\u8bd5\uff1atiyouju.exe status\uff1b\u5904\u7406\u8bd5\u5377\u7684\u6b65\u9aa4\u89c1\u4ed3\u5e93\u91cc\u7684 skills/tiyouju/SKILL.md'
    'keys' = '\u7b2c\u4e00\u6b21\u4f7f\u7528\uff1a\u8bf7\u4f7f\u7528\u8005\u5728\u9898\u6709\u636e\u7684\u201c\u8bbe\u7f6e \u2192 \u5e38\u7528 \u2192 \u586b\u5199\u6216\u66f4\u6362\u5bc6\u94a5\u201d\u91cc\u586b\u597d MinerU \u548c MiniMax \u7684\u5bc6\u94a5\uff08AI \u52a9\u624b\u4e0d\u8981\u4ee3\u586b\u5bc6\u94a5\uff09\u3002'
}

$Repo = 'CEHNICA/question-bank-card'
$AppDir = Join-Path $env:LOCALAPPDATA 'Programs\QuestionBankCard'
$App = Join-Path $AppDir 'QuestionBankCard.exe'
$Cli = Join-Path $AppDir 'tiyouju.exe'
$Data = Join-Path $env:LOCALAPPDATA 'QuestionBankCard'
$Mirror = "$env:TIYOUJU_MIRROR"

Write-Output (M 'finding')
$api = "https://api.github.com/repos/$Repo/releases/latest"
if ($env:TIYOUJU_VERSION) { $api = "https://api.github.com/repos/$Repo/releases/tags/v$($env:TIYOUJU_VERSION.TrimStart('v'))" }
try {
    $release = Invoke-RestMethod -Uri $api -Headers @{ 'User-Agent' = 'tiyouju-install'; 'Accept' = 'application/vnd.github+json' } -UseBasicParsing
} catch {
    throw (M 'offline')
}
$version = "$($release.tag_name)".TrimStart('v')
$setup = $release.assets | Where-Object { $_.name -like 'TiYouJu-Setup-*.exe' } | Select-Object -First 1
$sums = $release.assets | Where-Object { $_.name -eq 'SHA256SUMS.txt' } | Select-Object -First 1
if (-not $setup) { throw (M 'no_asset') }

$installed = ''
if (Test-Path -LiteralPath $App) { $installed = (Get-Item -LiteralPath $App).VersionInfo.ProductVersion }
if ($installed -eq $version -and $env:TIYOUJU_REINSTALL -ne '1') {
    Write-Output ((M 'already') + $version)
} else {
    $work = Join-Path $env:TEMP "tiyouju-install-$version"
    New-Item -ItemType Directory -Path $work -Force | Out-Null
    $setupPath = Join-Path $work $setup.name
    Write-Output ((M 'downloading') + $setup.name)
    Invoke-WebRequest -Uri ($Mirror + $setup.browser_download_url) -OutFile $setupPath -UseBasicParsing

    $expected = ''
    if ("$($setup.digest)" -like 'sha256:*') { $expected = "$($setup.digest)".Substring(7) }
    elseif ($sums) {
        $sumsPath = Join-Path $work 'SHA256SUMS.txt'
        Invoke-WebRequest -Uri ($Mirror + $sums.browser_download_url) -OutFile $sumsPath -UseBasicParsing
        $line = Get-Content -LiteralPath $sumsPath | Where-Object { $_ -match [regex]::Escape($setup.name) } | Select-Object -First 1
        if ($line) { $expected = ($line -split '\s+')[0] }
    }
    $actual = (Get-FileHash -LiteralPath $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()
    if (-not $expected -or $expected.ToLowerInvariant() -ne $actual) {
        Remove-Item -LiteralPath $setupPath -Force -ErrorAction SilentlyContinue
        throw (M 'bad_hash')
    }
    Write-Output (M 'hash_ok')

    $running = Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue
    if ($running) {
        Write-Output (M 'closing')
        $running | ForEach-Object { [void]$_.CloseMainWindow() }
        for ($i = 0; $i -lt 20 -and (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue); $i++) { Start-Sleep -Seconds 1 }
        Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
        if (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue) { throw (M 'still_running') }
    }
    $db = Join-Path $Data 'db.sqlite3'
    if (Test-Path -LiteralPath $db) {
        $backups = Join-Path $Data 'backups'
        New-Item -ItemType Directory -Path $backups -Force | Out-Null
        $backup = Join-Path $backups ("before-$version-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.sqlite3')
        Copy-Item -LiteralPath $db -Destination $backup
        Write-Output ((M 'backup') + $backup)
    }

    Write-Output (M 'installing')
    $process = Start-Process -FilePath $setupPath -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/CLOSEAPPLICATIONS' -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw ((M 'setup_failed') + $process.ExitCode) }
    Write-Output ((M 'installed') + (Get-Item -LiteralPath $App).VersionInfo.ProductVersion)
}

if ($env:TIYOUJU_NO_START -ne '1' -and -not (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue)) {
    Write-Output (M 'starting')
    Start-Process -FilePath $App -WorkingDirectory $AppDir
}
Write-Output ((M 'cli') + $Cli)
Write-Output (M 'cli_hint')
Write-Output (M 'keys')
