"""Write install.ps1 (the one-line installer for people and AI assistants).

PowerShell 5.1 reads a script fetched with ``irm ... | iex`` without knowing
its encoding, so the script itself must be plain ASCII.  The Chinese messages
live here, readable, and are written into the script as \\u escapes.

    python packaging/make_install_ps1.py      # rewrites install.ps1
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "install.ps1"

MESSAGES = {
    "finding": "正在查找题有据的最新版本……",
    "offline": "连不上 GitHub。请检查网络；国内网络可以先设置环境变量 TIYOUJU_MIRROR 为 GitHub 下载加速地址，或到 https://github.com/CEHNICA/question-bank-card/releases/latest 手动下载安装包。",
    "no_asset": "这个版本里没有找到安装包。",
    "already": "已安装这个版本：",
    "newer": "本机版本比公开安装包更新，已保留本机版本：",
    "downloading": "正在下载：",
    "bad_hash": "安装包的 SHA-256 校验值对不上，已停止安装（可能下载不完整或被改动）。请重新运行，或到 GitHub 发布页手动下载。",
    "hash_ok": "SHA-256 校验通过。",
    "closing": "正在关闭题有据……",
    "still_running": "题有据没能关掉，请先手动关掉它再运行一次。",
    "backup": "题库已备份到：",
    "installing": "正在安装（不会弹出窗口，约半分钟）……",
    "setup_failed": "安装程序出错，退出码：",
    "verify_failed": "安装尚未通过核验：软件或 AI 命令缺失、无法运行，或版本不一致。请保留错误信息并修复后再宣告安装完成。",
    "installed": "题有据已安装并通过核验，版本：",
    "starting": "正在打开题有据……",
    "cli": "给 AI 助手用的命令行：",
    "cli_hint": "试试：tiyouju.exe status；安装收尾见仓库 AGENTS.md 和 skills/tiyouju/references/install-finish.md。",
    "choices": "AI 助手下一步仅询问尚未选择、且当前客户端支持的选项：要安装题有据配套技能吗？桌面图标要显示还是隐藏？用户已给出选择就直接分别执行、核验，不重复确认；不要替用户默认选择。",
    "setup_hint": "先运行 tiyouju.exe assistant-setup --json 查看状态；用户同意后，用 --skill-dir 指定当前助手的技能目录，用 --desktop show 或 --desktop hide 设置桌面图标。",
    "old_cli": "这个版本尚不支持 assistant-setup，请按仓库的安装收尾说明处理，或升级到 1.10.14 及以上版本后再使用该命令。",
    "invite": "安装收尾后请直接告诉用户：以后有题目或试卷，可以直接发给我，我会通过题有据帮你整理、核对，并保留原卷出处。",
    "keys": "需要云识读时，再请使用者在题有据设置中自行填写所需服务密钥；云识读不可用时仍可整理现有题目和核对出处。AI 助手不要代填或读取密钥。",
}


def escape(text: str) -> str:
    return "".join(ch if 32 <= ord(ch) < 127 and ch not in "'\\" else
                   ("''" if ch == "'" else f"\\u{ord(ch):04x}") for ch in text)


TEMPLATE = r"""# TiYouJu (question-bank-card) one-line installer / updater for Windows.
#
#   irm https://github.com/CEHNICA/question-bank-card/releases/latest/download/install.ps1 | iex
#
# Finds the latest release on GitHub, downloads the installer, checks its
# SHA-256 (GitHub's asset digest, else SHA256SUMS.txt), backs up the question
# bank database, closes a running app, installs silently for the current user
# and starts the app.  It never asks for or touches API keys.
#
# Optional environment variables:
#   TIYOUJU_VERSION   install this version (e.g. 1.9.0) instead of the latest
#   TIYOUJU_MIRROR    prefix for download URLs (a GitHub download mirror)
#   TIYOUJU_REINSTALL set to 1 to reinstall the same version
#   TIYOUJU_NO_START  set to 1 to leave the app closed afterwards
#
# This file is generated by packaging/make_install_ps1.py (keep it ASCII).

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

function M([string]$key) { return [regex]::Unescape($Messages[$key]) }
function App-Version([string]$text) {
    try {
        $parsed = [version]$text
        if ($parsed.Build -lt 0) { throw 'missing patch version' }
        return [version]$parsed.ToString(3)
    } catch { throw (M 'verify_failed') }
}
$Messages = @{
@@MESSAGES@@
}

$Repo = 'CEHNICA/question-bank-card'
$AppDir = Join-Path $env:LOCALAPPDATA 'Programs\QuestionBankCard'
$App = Join-Path $AppDir 'QuestionBankCard.exe'
$Cli = Join-Path $AppDir 'tiyouju.exe'
$Data = Join-Path $env:LOCALAPPDATA 'QuestionBankCard'
$Mirror = "$env:TIYOUJU_MIRROR"

Write-Output (M 'finding')
$api = "https://api.github.com/repos/$Repo/releases/latest"
if ($env:TIYOUJU_VERSION) { $api = "https://api.github.com/repos/$Repo/releases/tags/v$($env:TIYOUJU_VERSION.TrimStart('v'))" }
try {
    $release = Invoke-RestMethod -Uri $api -Headers @{ 'User-Agent' = 'tiyouju-install'; 'Accept' = 'application/vnd.github+json' } -UseBasicParsing
} catch {
    throw (M 'offline')
}
$version = "$($release.tag_name)".TrimStart('v')
$setup = $release.assets | Where-Object { $_.name -like 'TiYouJu-Setup-*.exe' } | Select-Object -First 1
$sums = $release.assets | Where-Object { $_.name -eq 'SHA256SUMS.txt' } | Select-Object -First 1
if (-not $setup) { throw (M 'no_asset') }

$installed = ''
if (Test-Path -LiteralPath $App) { $installed = (Get-Item -LiteralPath $App).VersionInfo.ProductVersion }
$keepInstalled = $false
if ($installed) {
    $installedVersion = App-Version $installed
    $releaseVersion = App-Version $version
    $keepInstalled = ($installedVersion -eq $releaseVersion -and $env:TIYOUJU_REINSTALL -ne '1') -or (-not $env:TIYOUJU_VERSION -and $installedVersion -gt $releaseVersion)
}
if ($keepInstalled) {
    if ($installedVersion -gt $releaseVersion) { Write-Output ((M 'newer') + $installedVersion) }
    else { Write-Output ((M 'already') + $installedVersion) }
} else {
    $work = Join-Path $env:TEMP "tiyouju-install-$version"
    New-Item -ItemType Directory -Path $work -Force | Out-Null
    $setupPath = Join-Path $work $setup.name
    Write-Output ((M 'downloading') + $setup.name)
    Invoke-WebRequest -Uri ($Mirror + $setup.browser_download_url) -OutFile $setupPath -UseBasicParsing

    $expected = ''
    if ("$($setup.digest)" -like 'sha256:*') { $expected = "$($setup.digest)".Substring(7) }
    elseif ($sums) {
        $sumsPath = Join-Path $work 'SHA256SUMS.txt'
        Invoke-WebRequest -Uri ($Mirror + $sums.browser_download_url) -OutFile $sumsPath -UseBasicParsing
        $line = Get-Content -LiteralPath $sumsPath | Where-Object { $_ -match [regex]::Escape($setup.name) } | Select-Object -First 1
        if ($line) { $expected = ($line -split '\s+')[0] }
    }
    $actual = (Get-FileHash -LiteralPath $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()
    if (-not $expected -or $expected.ToLowerInvariant() -ne $actual) {
        Remove-Item -LiteralPath $setupPath -Force -ErrorAction SilentlyContinue
        throw (M 'bad_hash')
    }
    Write-Output (M 'hash_ok')

    $running = Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue
    if ($running) {
        Write-Output (M 'closing')
        $running | ForEach-Object { [void]$_.CloseMainWindow() }
        for ($i = 0; $i -lt 20 -and (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue); $i++) { Start-Sleep -Seconds 1 }
        Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
        if (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue) { throw (M 'still_running') }
    }
    $db = Join-Path $Data 'db.sqlite3'
    if (Test-Path -LiteralPath $db) {
        $backups = Join-Path $Data 'backups'
        New-Item -ItemType Directory -Path $backups -Force | Out-Null
        $backup = Join-Path $backups ("before-$version-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.sqlite3')
        Copy-Item -LiteralPath $db -Destination $backup
        Write-Output ((M 'backup') + $backup)
    }

    Write-Output (M 'installing')
    $process = Start-Process -FilePath $setupPath -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/CLOSEAPPLICATIONS', '/MERGETASKS=!desktopicon' -WindowStyle Hidden -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw ((M 'setup_failed') + $process.ExitCode) }
}

if (-not (Test-Path -LiteralPath $App -PathType Leaf) -or -not (Test-Path -LiteralPath $Cli -PathType Leaf)) { throw (M 'verify_failed') }
$verifiedVersion = App-Version ((Get-Item -LiteralPath $App).VersionInfo.ProductVersion)
$expectedVersion = App-Version $version
if ($keepInstalled) { $expectedVersion = $installedVersion }
if ($verifiedVersion -ne $expectedVersion) { throw (M 'verify_failed') }
try { $cliVersion = ((& $Cli --version 2>&1) -join '').Trim() }
catch { throw (M 'verify_failed') }
if ($LASTEXITCODE -ne 0 -or $cliVersion -ne "tiyouju $($verifiedVersion.ToString(3))") { throw (M 'verify_failed') }
Write-Output ((M 'installed') + $verifiedVersion.ToString(3))

if ($env:TIYOUJU_NO_START -ne '1' -and -not (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue)) {
    Write-Output (M 'starting')
    Start-Process -FilePath $App -WorkingDirectory $AppDir -WindowStyle Hidden
}
Write-Output ((M 'cli') + $Cli)
Write-Output (M 'cli_hint')
Write-Output (M 'choices')
if ($verifiedVersion -ge [version]'1.10.14') { Write-Output (M 'setup_hint') }
else { Write-Output (M 'old_cli') }
Write-Output (M 'invite')
Write-Output (M 'keys')
"""


def render() -> str:
    lines = [f"    '{key}' = '{escape(text)}'" for key, text in MESSAGES.items()]
    script = TEMPLATE.replace("@@MESSAGES@@", "\n".join(lines))
    script.encode("ascii")
    return script.replace("\n", "\r\n")


def main() -> None:
    TARGET.write_bytes(render().encode("ascii"))
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
