"""Write install.ps1 (the one-line installer for people and AI assistants).

PowerShell 5.1 reads a script fetched with ``irm ... | iex`` without knowing
its encoding, so the script itself must be plain ASCII.  The Chinese messages
live here, readable, and are written into the script as \\u escapes.

    python packaging/make_install_ps1.py      # rewrites install.ps1
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "install.ps1"

MESSAGES = {
    "finding": "正在查找题有据的最新版本……",
    "offline": "连不上 GitHub。请检查网络；国内网络可以先设置环境变量 TIYOUJU_MIRROR 为 GitHub 下载加速地址，或到 https://github.com/CEHNICA/question-bank-card/releases/latest 手动下载安装包。",
    "no_asset": "这个版本里没有找到安装包。",
    "already": "已经是最新版：",
    "downloading": "正在下载：",
    "bad_hash": "安装包的 SHA-256 校验值对不上，已停止安装（可能下载不完整或被改动）。请重新运行，或到 GitHub 发布页手动下载。",
    "hash_ok": "SHA-256 校验通过。",
    "closing": "正在关闭题有据……",
    "still_running": "题有据没能关掉，请先手动关掉它再运行一次。",
    "backup": "题库已备份到：",
    "installing": "正在安装（不会弹出窗口，约半分钟）……",
    "setup_failed": "安装程序出错，退出码：",
    "installed": "题有据已安装，版本：",
    "starting": "正在打开题有据……",
    "cli": "给 AI 助手用的命令行：",
    "cli_hint": "试试：tiyouju.exe status；处理试卷的步骤见仓库里的 skills/tiyouju/SKILL.md",
    "keys": "第一次使用：请使用者在题有据的“设置 → 常用 → 填写或更换密钥”里填好 MinerU 和 MiniMax 的密钥（AI 助手不要代填密钥）。",
}


def escape(text: str) -> str:
    return "".join(ch if 32 <= ord(ch) < 127 and ch not in "'\\" else
                   ("''" if ch == "'" else f"\\u{ord(ch):04x}") for ch in text)


TEMPLATE = r"""# TiYouJu (question-bank-card) one-line installer / updater for Windows.
#
#   irm https://github.com/CEHNICA/question-bank-card/releases/latest/download/install.ps1 | iex
#
# Finds the latest release on GitHub, downloads the installer, checks its
# SHA-256 (GitHub's asset digest, else SHA256SUMS.txt), backs up the question
# bank database, closes a running app, installs silently for the current user
# and starts the app.  It never asks for or touches API keys.
#
# Optional environment variables:
#   TIYOUJU_VERSION   install this version (e.g. 1.9.0) instead of the latest
#   TIYOUJU_MIRROR    prefix for download URLs (a GitHub download mirror)
#   TIYOUJU_REINSTALL set to 1 to reinstall the same version
#   TIYOUJU_NO_START  set to 1 to leave the app closed afterwards
#
# This file is generated by packaging/make_install_ps1.py (keep it ASCII).

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

function M([string]$key) { return [regex]::Unescape($Messages[$key]) }
$Messages = @{
@@MESSAGES@@
}

$Repo = 'CEHNICA/question-bank-card'
$AppDir = Join-Path $env:LOCALAPPDATA 'Programs\QuestionBankCard'
$App = Join-Path $AppDir 'QuestionBankCard.exe'
$Cli = Join-Path $AppDir 'tiyouju.exe'
$Data = Join-Path $env:LOCALAPPDATA 'QuestionBankCard'
$Mirror = "$env:TIYOUJU_MIRROR"

Write-Output (M 'finding')
$api = "https://api.github.com/repos/$Repo/releases/latest"
if ($env:TIYOUJU_VERSION) { $api = "https://api.github.com/repos/$Repo/releases/tags/v$($env:TIYOUJU_VERSION.TrimStart('v'))" }
try {
    $release = Invoke-RestMethod -Uri $api -Headers @{ 'User-Agent' = 'tiyouju-install'; 'Accept' = 'application/vnd.github+json' } -UseBasicParsing
} catch {
    throw (M 'offline')
}
$version = "$($release.tag_name)".TrimStart('v')
$setup = $release.assets | Where-Object { $_.name -like 'TiYouJu-Setup-*.exe' } | Select-Object -First 1
$sums = $release.assets | Where-Object { $_.name -eq 'SHA256SUMS.txt' } | Select-Object -First 1
if (-not $setup) { throw (M 'no_asset') }

$installed = ''
if (Test-Path -LiteralPath $App) { $installed = (Get-Item -LiteralPath $App).VersionInfo.ProductVersion }
if ($installed -eq $version -and $env:TIYOUJU_REINSTALL -ne '1') {
    Write-Output ((M 'already') + $version)
} else {
    $work = Join-Path $env:TEMP "tiyouju-install-$version"
    New-Item -ItemType Directory -Path $work -Force | Out-Null
    $setupPath = Join-Path $work $setup.name
    Write-Output ((M 'downloading') + $setup.name)
    Invoke-WebRequest -Uri ($Mirror + $setup.browser_download_url) -OutFile $setupPath -UseBasicParsing

    $expected = ''
    if ("$($setup.digest)" -like 'sha256:*') { $expected = "$($setup.digest)".Substring(7) }
    elseif ($sums) {
        $sumsPath = Join-Path $work 'SHA256SUMS.txt'
        Invoke-WebRequest -Uri ($Mirror + $sums.browser_download_url) -OutFile $sumsPath -UseBasicParsing
        $line = Get-Content -LiteralPath $sumsPath | Where-Object { $_ -match [regex]::Escape($setup.name) } | Select-Object -First 1
        if ($line) { $expected = ($line -split '\s+')[0] }
    }
    $actual = (Get-FileHash -LiteralPath $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()
    if (-not $expected -or $expected.ToLowerInvariant() -ne $actual) {
        Remove-Item -LiteralPath $setupPath -Force -ErrorAction SilentlyContinue
        throw (M 'bad_hash')
    }
    Write-Output (M 'hash_ok')

    $running = Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue
    if ($running) {
        Write-Output (M 'closing')
        $running | ForEach-Object { [void]$_.CloseMainWindow() }
        for ($i = 0; $i -lt 20 -and (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue); $i++) { Start-Sleep -Seconds 1 }
        Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
        if (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue) { throw (M 'still_running') }
    }
    $db = Join-Path $Data 'db.sqlite3'
    if (Test-Path -LiteralPath $db) {
        $backups = Join-Path $Data 'backups'
        New-Item -ItemType Directory -Path $backups -Force | Out-Null
        $backup = Join-Path $backups ("before-$version-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.sqlite3')
        Copy-Item -LiteralPath $db -Destination $backup
        Write-Output ((M 'backup') + $backup)
    }

    Write-Output (M 'installing')
    $process = Start-Process -FilePath $setupPath -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/CLOSEAPPLICATIONS' -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw ((M 'setup_failed') + $process.ExitCode) }
    Write-Output ((M 'installed') + (Get-Item -LiteralPath $App).VersionInfo.ProductVersion)
}

if ($env:TIYOUJU_NO_START -ne '1' -and -not (Get-Process -Name 'QuestionBankCard' -ErrorAction SilentlyContinue)) {
    Write-Output (M 'starting')
    Start-Process -FilePath $App -WorkingDirectory $AppDir
}
Write-Output ((M 'cli') + $Cli)
Write-Output (M 'cli_hint')
Write-Output (M 'keys')
"""


def render() -> str:
    lines = [f"    '{key}' = '{escape(text)}'" for key, text in MESSAGES.items()]
    script = TEMPLATE.replace("@@MESSAGES@@", "\n".join(lines))
    script.encode("ascii")
    return script.replace("\n", "\r\n")


def main() -> None:
    TARGET.write_bytes(render().encode("ascii"))
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
