# Generated by Django 5.2.17 on 2026-09-26 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=8)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("source_path", models.CharField(max_length=500)),
                ("render_path", models.CharField(blank=True, max_length=500)),
                ("zip_path", models.CharField(blank=True, max_length=500)),
                ("pages", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("parsing", "MinerU 解析中"),
                            ("segmenting", "切题中"),
                            ("reading", "AI 读题中"),
                            ("ready", "待你终审"),
                            ("failed", "失败"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("notes", models.JSONField(default=list)),
                ("imported_from", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("section", models.CharField(blank=True, max_length=120)),
                ("question_type", models.CharField(default="unknown", max_length=24)),
                ("regions", models.JSONField(default=list)),
                ("regions_auto", models.JSONField(default=list)),
                ("start_source", models.CharField(default="mineru", max_length=16)),
                ("figure_candidates", models.JSONField(default=list)),
                ("figures", models.JSONField(default=list)),
                ("read_a", models.JSONField(default=dict)),
                ("read_b", models.JSONField(default=dict)),
                ("read_c", models.JSONField(default=dict)),
                ("stem", models.TextField(blank=True)),
                ("options", models.JSONField(default=dict)),
                ("text_source", models.CharField(blank=True, max_length=16)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "等待识读"),
                            ("reading", "识读中"),
                            ("green", "两次识读一致"),
                            ("yellow", "请看一眼"),
                            ("red", "识读失败"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("flags", models.JSONField(default=list)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("edited", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, default="")),
                ("analysis", models.TextField(blank=True, default="")),
                ("reread_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["number", "id"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=40)),
                ("page_idx", models.PositiveIntegerField()),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("text", models.TextField(blank=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="core.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "seq"), name="unique_block_seq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublishedQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("number", models.PositiveIntegerField()),
                ("question_type", models.CharField(max_length=24)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="published",
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64)),
                ("search_text", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="core.paper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "version"), name="unique_question_version"
                    )
                ],
            },
        ),
    ]
