# Generated by Django 5.2.17 on 2026-09-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="photos",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
