# Generated by Django 5.2.17 on 2026-09-27

import core.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_import_structure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["number", "id"],
            },
        ),
        migrations.AlterModelManagers(
            name="question",
            managers=[
                ("objects", core.models.ActiveQuestionManager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="QuestionDeletionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_deletion_batches",
                        to="core.paper",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="deletion_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="core.questiondeletionbatch",
            ),
        ),
    ]
