# Generated by Django 5.2.17 on 2026-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_resegment_source_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
