# Generated by Django 5.2.17 on 2026-10-01 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_approval_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedquestion",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="publishedquestion",
            name="tags_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="origin",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="question",
            name="type_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LibraryJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("tags", "知识点"), ("answer", "AI 参考答案")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "进行中"),
                            ("done", "完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.publishedquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
