# Generated by Django 5.2.17 on 2026-10-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_library_extras_and_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_idx", models.PositiveIntegerField()),
                ("bbox", models.JSONField()),
                ("target", models.CharField(max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "进行中"),
                            ("done", "完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("engine", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_reads",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
